version: '3'
services:
  agent:
    image: "datadog/agent:6.4.2"
    environment:
      - DD_API_KEY
      - DD_APM_ENABLED=true
    ports:
      - 8126:8126
  web:
    environment:
      - FLASK_APP=api.py
      - FLASK_DEBUG=1
    build: .
    command: flask run --port=5000 --host=0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - "./app:/app"
    depends_on:
      - agent
      - db
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    
