apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensors-api
spec:
  selector:
    matchLabels:
      app: sensors-api
  template:
    metadata:
      labels:
        app: sensors-api
    spec:
      containers:
      - name: sensors-api
        image: sensors-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5002
        env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DOGSTATSD_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: FLASK_APP
          value: 'sensors'
        - name: DD_LOGS_INJECTION
          value: 'true'
        - name: FLASK_DEBUG
          value: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: sensors-api
spec:
  selector:
    app: sensors-api
  ports:
  - name: http
    protocol: TCP
    port: 5002
  type: NodePort
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-datadog-confd
  namespace: default
