apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
      - name: frontend-service
        image: burningion/k8s-distributed-tracing-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5005
          hostPort: 5005
          name: frontendport
          protocol: TCP
        volumeMounts:
        - name: flasklogs
          mountPath: /var/log/flask
        env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DOGSTATSD_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DATADOG_SERVICE_NAME
          value: 'frontend-service'
        - name: FLASK_APP
          value: 'api'
        - name: DD_LOGS_INJECTION
          value: 'true'
        - name: FLASK_DEBUG
          value: '1'
        - name: FLASK_RUN_PORT
          value: '5005'
      volumes:
        - hostPath:
            path: /var/log/flask
          name: flasklogs

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-service
  ports:
  - name: http
    protocol: TCP
    port: 5005
    nodePort: 30001
  type: NodePort
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-datadog-confd
  namespace: default
data:
  flasklogs.yaml: |-
    init_config:
    instances:
    logs:
    - type: file
      path: /var/log/flask/mylog.json
      service: flask
      source: python
      sourcecategory: sourcecode 
